### ISSUE TITLE
Is there a client side js version of this library ?

### ISSUE THREAD

**Issue by jitenoswal** [bluesmoon/node-faststats#10]
This library is really awesome. But I was looking for using something on client-side to do this math. Is there a client side js version of this library ?

Not really a issue but just a different requirement.

**Comment by bluesmoon** [comment]
The js should work as is in a browser. There aren't any dependencies.

**Comment by bluesmoon** [comment]
Yeah, this will work as-is in a modern browser (ie, with modern `Array` object methods) or with a polyfill for older browsers.
