### ISSUE TITLE
Make a release using `npm version` so that README shows up on npmjs.com

### ISSUE THREAD

**Issue by icyflame** [bluesmoon/node-faststats#12]

**Comment by icyflame** [comment]
ping @bluesmoon

**Comment by bluesmoon** [comment]
I have no idea what this means.

**Comment by icyflame** [comment]
Well, what I meant was that currently on this pacakge's npm page :- http://npmjs.com/package/node-faststats , the README doesn't show up, there's this :- 

![image](https://cloud.githubusercontent.com/assets/3668034/8484443/6bd126ca-2115-11e5-9151-f2156f82c273.png)

Once you do 
```shell
npm version 0.0.3
npm publish
```

in your shell, from inside this package, the changes will be published to npm and everyone who visits that page will be able to see the README. 

You should also note that the changes that you push to Github are not automatically updated to NPM, so, you must publish a new version for everyone else to enjoy the bug-fixes, etc that have happened since the last release.

**Comment by bluesmoon** [comment]
yeah, I know I have to publish, but didn't know about npm version.  Is that something new?  Sorry, but I haven't actually used node.js since 2012, so my information may be outdated.

**Comment by icyflame** [comment]
Well, `npm version` is not something ground breaking or anything, but it
was added some time ago, I guess.

It bumps the version number in the package.json file and also, creates a
git tag. And then, when followed up by `npm publish`, it works well! Just
simplifies the process of releasing!

**Comment by bluesmoon** [comment]
Turns out I didn't need to do `npm version`.  I just had to republish due to changes on the npm site.

**Comment by bluesmoon** [comment]
ok, I always update the version number by hand
