### ISSUE TITLE
Standard deviation can be NaN for odd count of the same elements

### ISSUE THREAD

**Issue by Schniz** [bluesmoon/node-faststats#18]
Hi!
first of all, thanks for this package. It is very good and handy 😸

It seems as if the `stddev` function returns `NaN` on arrays that contain the same element but have an odd-number length (`[1, 1, 1]` returns `NaN` where `[1, 1]` returns `0`)

### Expected behavior:

```js
const { Stats } = require('fast-stats');
const odd = new Stats().push(0.11, 0.11, 0.11); // 0
const even = new Stats().push(0.11, 0.11); // 0
```

### Actual behavior:

```js
const { Stats } = require('fast-stats');
const odd = new Stats().push(0.11, 0.11, 0.11); // NaN
const even = new Stats().push(0.11, 0.11); // 0
```

Here's it on RunKit:
https://runkit.com/schniz/fast-stats-nan-stddev

![RunKit screenshot](https://user-images.githubusercontent.com/2054772/50962971-1d608d80-14d4-11e9-841f-c158fcc638cf.png)

**Comment by bluesmoon** [comment]
Good catch.  This is caused by floating point weirdness where `0.33*0.33 == 0.10890000000000001` instead of `0.1089`, so we end up taking the square root of a negative number.
