### ISSUE TITLE
Negative values with buckets

### ISSUE THREAD

**Issue by tcf909** [bluesmoon/node-faststats#20]
Hello,

I really appreciate the work you have done with this library.

I noticed negative values do not really work with buckets. Have you noticed that or given any thought to it?

I noticed the other issue that says buckets should work but geo methods will not as they require positive numbers, but I am not using any geo functions.

It looks like buckets would need to be stored in an object and a sorted list of buckets in an array to support this. Currently all buckets are stored in an array which means you end up with:

Array[-124] = (tuple)

And a loop that uses Array.length which is actually 0 given a negative value doesn't get stored in the array data structure but rather the array object (the same place the .length property is stored for instance).

**Comment by tcf909** [comment]
A clarification: using bucket_precision (vs my own defined buckets)

**Comment by bluesmoon** [comment]
I don't think it will work with bucket precision. I'm out on vacation at the moment so can't check for sure. I think the solution might be to have a separate object for positive and negative values both of which are normalised to positive.

**Comment by tcf909** [comment]
We went ahead and moved buckets to use an object for the actual buckets (key = value, value = count) and a sorted array to index the buckets. 

Appreciate the reply.
